version: "3.9"
services:
  backend:
    hostname: weather_backend
    container_name: weather_backend
    build:
      context: .
      dockerfile: WeatherBackend/Dockerfile
    depends_on:
      - sqldata
    ports:
      - "8000:8080"
  grabber:
    hostname: weather_grabber
    container_name: weather_grabber
    build:
      context: .
      dockerfile: WeatherGrabber/Dockerfile
    depends_on:
      - sqldata
  telegram:
    hostname: weather_telegram
    container_name: weather_telegram
    build:
      context: .
      dockerfile: WeatherTelegramService/Dockerfile
    depends_on:
      - sqldata
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: weather_rabbit
    ports:
        - "5672:5672"
        - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: "weather_user"
        RABBITMQ_DEFAULT_PASS: "weather_user"
        RABBITMQ_DEFAULT_VHOST: "/"